// <auto-generated />
using ECom_MS.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EComMS.Services.CouponAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240420053719_SeedCoupons")]
    partial class SeedCoupons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECom_MS.Services.CouponAPI.Entities.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "ABC143",
                            DiscountAmount = 49.990000000000002,
                            MinAmount = 1000
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "Coupon10",
                            DiscountAmount = 10.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "Coupon20",
                            DiscountAmount = 20.0,
                            MinAmount = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
